# SPDX-License-Identifier: MIT AND Commons-Clause-1.0
# Copyright (c) 2026 nvk
"""Font categories — a font can belong to multiple categories."""

CATEGORIES = {
    "3d": "3D effects, depth, perspective",
    "block": "Heavy block/box characters, filled shapes",
    "bubble": "Rounded, bubble-like characters",
    "classic": "Traditional FIGlet style",
    "cursive": "Script, handwriting, flowing",
    "decorative": "Ornamental, fancy, elaborate",
    "digital": "LED, LCD, dot matrix, pixel",
    "graffiti": "Street art, urban style",
    "gothic": "Dark, medieval, blackletter",
    "lean": "Thin, lightweight strokes",
    "mini": "Very small, compact (1-3 lines)",
    "mono": "Monospace, fixed-width terminal style",
    "sans": "Clean sans-serif letterforms",
    "serif": "Serif letterforms",
    "shadow": "Shadow effects",
    "slant": "Italic/slanted/oblique",
    "tech": "Futuristic, sci-fi, cyber",
    "weird": "Abstract, artistic, hard to read",
}

# Maps font name -> list of category tags
FONT_TAGS: dict[str, list[str]] = {
    # 0-9
    "1Row": ["mini", "mono"],
    "3-D": ["3d", "classic"],
    "3D Diagonal": ["3d", "decorative"],
    "3D-ASCII": ["3d", "serif"],
    "3x5": ["mini", "digital"],
    "4Max": ["block", "classic"],
    "5 Line Oblique": ["slant", "lean"],
    # A
    "AMC 3 Line": ["mini", "lean"],
    "AMC 3 Liv1": ["decorative", "weird"],
    "AMC AAA01": ["decorative", "serif"],
    "AMC Neko": ["decorative", "block"],
    "AMC Razor": ["tech", "decorative"],
    "AMC Razor2": ["tech", "decorative"],
    "AMC Slash": ["lean", "classic"],
    "AMC Slider": ["block", "sans"],
    "AMC Thin": ["lean", "mono"],
    "AMC Tubes": ["classic", "sans"],
    "AMC Untitled": ["cursive", "lean"],
    "ANSI Compact": ["block", "mini"],
    "ANSI Regular": ["block", "sans"],
    "ANSI Shadow": ["block", "shadow", "3d"],
    "ASCII 12": ["mono", "serif"],
    "ASCII 9": ["mono", "classic"],
    "ASCII New Roman": ["serif", "mini"],
    "Acrobatic": ["decorative", "weird"],
    "Alligator": ["decorative", "digital"],
    "Alligator2": ["decorative", "digital"],
    "Alpha": ["decorative", "3d"],
    "Alphabet": ["mini", "sans"],
    "Arrows": ["lean", "tech"],
    "Avatar": ["classic", "lean"],
    # B
    "B1FF": ["mini", "weird"],
    "Babyface Lame": ["cursive", "decorative"],
    "Babyface Leet": ["cursive", "decorative"],
    "Banner": ["classic", "block"],
    "Banner3": ["block", "classic"],
    "Banner3-D": ["block", "3d", "shadow"],
    "Banner4": ["block", "classic"],
    "Barbwire": ["lean", "tech"],
    "Basic": ["classic", "serif"],
    "Bear": ["decorative", "weird"],
    "Bell": ["classic", "serif"],
    "Benjamin": ["mini", "mono"],
    "Big": ["classic", "sans"],
    "Big ASCII 12": ["mono", "serif"],
    "Big ASCII 9": ["mono", "classic"],
    "Big Chief": ["classic", "lean"],
    "Big Money-ne": ["3d", "classic"],
    "Big Money-nw": ["3d", "classic"],
    "Big Money-se": ["3d", "classic"],
    "Big Money-sw": ["3d", "classic"],
    "Big Mono 12": ["block", "mono"],
    "Big Mono 9": ["block", "mono"],
    "Bigfig": ["mini", "lean"],
    "Binary": ["mini", "digital"],
    "Block": ["block", "lean"],
    "Blocks": ["block", "decorative"],
    "Bloody": ["block", "gothic"],
    "BlurVision ASCII": ["block", "digital"],
    "Bolger": ["classic", "sans"],
    "Braced": ["lean", "classic"],
    "Bright": ["block", "sans"],
    "Broadway": ["serif", "decorative"],
    "Broadway KB": ["mini", "sans"],
    "Bubble": ["bubble", "decorative"],
    "Bulbhead": ["block", "sans"],
    # C
    "Caligraphy": ["cursive", "decorative"],
    "Caligraphy2": ["cursive", "decorative"],
    "Calvin S": ["mini", "mono"],
    "Cards": ["decorative", "block"],
    "Catwalk": ["lean", "tech"],
    "Chiseled": ["decorative", "gothic"],
    "Chunky": ["block", "mono"],
    "Circle": ["bubble", "mini"],
    "Classy": ["block", "serif"],
    "Coder Mini": ["block", "mini"],
    "Coinstak": ["lean", "tech"],
    "Cola": ["cursive", "decorative"],
    "Colossal": ["block", "classic"],
    "Computer": ["digital", "classic"],
    "Contessa": ["mini", "lean"],
    "Contrast": ["block", "sans"],
    "Cosmike": ["decorative", "classic"],
    "Cosmike2": ["decorative", "classic"],
    "Crawford": ["classic", "serif"],
    "Crawford2": ["classic", "serif"],
    "Crazy": ["cursive", "decorative", "weird"],
    "Cricket": ["block", "mono"],
    "Cursive": ["cursive", "lean"],
    "Cyberlarge": ["block", "tech"],
    "Cybermedium": ["tech", "sans"],
    "Cybersmall": ["mini", "tech"],
    "Cygnet": ["mini", "lean"],
    # D
    "DANC4": ["weird", "decorative"],
    "DOS Rebel": ["block", "tech"],
    "DWhistled": ["weird", "mini"],
    "Dancing Font": ["decorative", "classic"],
    "Decimal": ["mini", "digital"],
    "Def Leppard": ["decorative", "graffiti"],
    "Delta Corps Priest 1": ["block", "gothic"],
    "DiamFont": ["block", "digital"],
    "Diamond": ["lean", "tech"],
    "Diet Cola": ["cursive", "decorative"],
    "Digital": ["digital", "mini"],
    "Doh": ["block", "classic"],
    "Doom": ["classic", "sans"],
    "Dot Matrix": ["digital", "decorative"],
    "Double": ["classic", "sans"],
    "Double Shorts": ["mini", "mono"],
    "Dr Pepper": ["classic", "lean"],
    # E
    "Efti Chess": ["decorative", "weird"],
    "Efti Font": ["classic", "weird"],
    "Efti Italic": ["slant", "weird"],
    "Efti Piti": ["mini", "mono"],
    "Efti Robot": ["classic", "sans"],
    "Efti Wall": ["decorative", "weird"],
    "Efti Water": ["mini", "lean"],
    "Electronic": ["block", "digital"],
    "Elite": ["block", "decorative"],
    "Emboss": ["mono", "block", "mini"],
    "Emboss 2": ["mono", "block", "mini"],
    "Epic": ["classic", "sans"],
    # F
    "Fender": ["classic", "sans"],
    "Filter": ["block", "digital"],
    "Fire Font-k": ["decorative", "cursive"],
    "Fire Font-s": ["decorative", "cursive"],
    "Flipped": ["classic", "sans"],
    "Flower Power": ["decorative", "cursive"],
    "Font Font": ["block", "weird"],
    "Four Tops": ["mini", "lean"],
    "Fraktur": ["gothic", "decorative"],
    "Fun Face": ["decorative", "weird"],
    "Fun Faces": ["decorative", "weird"],
    "Future": ["mono", "mini", "block"],
    "Future Smooth": ["mono", "mini", "lean"],
    "Future Thin": ["mono", "mini", "lean"],
    "Fuzzy": ["classic", "sans"],
    # G
    "Georgi16": ["serif", "classic"],
    "Georgia11": ["serif", "classic"],
    "Ghost": ["decorative", "classic"],
    "Ghoulish": ["cursive", "weird"],
    "Glenyn": ["classic", "sans"],
    "Goofy": ["decorative", "weird"],
    "Gothic": ["gothic", "lean"],
    "Graceful": ["classic", "sans"],
    "Gradient": ["decorative", "block", "weird"],
    "Graffiti": ["graffiti", "serif"],
    "Greek": ["classic", "sans"],
    # H
    "Heart Left": ["decorative", "mini", "bubble"],
    "Heart Right": ["decorative", "mini", "bubble"],
    "Henry 3D": ["3d", "sans"],
    "Hex": ["digital", "mini", "mono"],
    "Hieroglyphs": ["decorative", "weird"],
    "Hollywood": ["cursive", "slant"],
    "Horizontal Left": ["block", "decorative"],
    "Horizontal Right": ["block", "decorative"],
    # I
    "ICL-1900": ["weird", "digital"],
    "Impossible": ["3d", "decorative"],
    "Invita": ["cursive", "slant"],
    "Isometric1": ["3d", "decorative"],
    "Isometric2": ["3d", "decorative"],
    "Isometric3": ["3d", "decorative"],
    "Isometric4": ["3d", "decorative"],
    "Italic": ["slant", "mini", "lean"],
    "Ivrit": ["classic", "sans"],
    # J
    "JS Block Letters": ["block", "sans", "mini"],
    "JS Bracket Letters": ["classic", "sans"],
    "JS Capital Curves": ["cursive", "lean"],
    "JS Cursive": ["cursive", "lean", "mini"],
    "JS Stick Letters": ["mini", "lean", "sans"],
    "Jacky": ["classic", "serif"],
    "Jazmine": ["classic", "sans"],
    "Jerusalem": ["classic", "sans"],
    # K
    "Katakana": ["tech", "weird"],
    "Kban": ["classic", "sans"],
    "Keyboard": ["block", "decorative", "digital"],
    "Knob": ["block", "sans"],
    "Konto": ["mini", "mono", "lean"],
    "Konto Slant": ["mini", "slant", "lean"],
    # L
    "LCD": ["digital", "lean", "mini"],
    "Larry 3D": ["3d", "serif"],
    "Larry 3D 2": ["3d", "serif"],
    "Lean": ["lean", "slant"],
    "Letter": ["block", "classic", "sans"],
    "Letters": ["classic", "lean", "sans"],
    "Lil Devil": ["decorative", "weird"],
    "Line Blocks": ["block", "sans"],
    "Linux": ["mini", "mono", "lean"],
    "Lockergnome": ["mini", "mono"],
    # M
    "Madrid": ["mini", "sans"],
    "Marquee": ["decorative", "classic"],
    "Maxfour": ["mini", "lean"],
    "Merlin1": ["decorative", "serif", "classic"],
    "Merlin2": ["decorative", "cursive"],
    "Mike": ["mini", "lean"],
    "Mini": ["mini", "lean"],
    "Mirror": ["classic", "serif"],
    "Mnemonic": ["mini", "mono"],
    "Modular": ["block", "classic"],
    "Mono 12": ["block", "mono", "serif"],
    "Mono 9": ["mono", "block"],
    "Morse": ["mini", "mono", "digital"],
    "Morse2": ["mini", "mono", "digital"],
    "Moscow": ["block", "classic"],
    "Mshebrew210": ["weird", "mini"],
    "Muzzle": ["lean", "tech"],
    # N
    "NScript": ["cursive", "decorative"],
    "NT Greek": ["serif", "classic"],
    "NV Script": ["cursive", "decorative"],
    "Nancyj": ["classic", "serif"],
    "Nancyj-Fancy": ["classic", "decorative", "serif"],
    "Nancyj-Improved": ["classic", "serif"],
    "Nancyj-Underlined": ["classic", "serif", "decorative"],
    "Nipples": ["decorative", "classic"],
    # O
    "O8": ["classic", "sans"],
    "OS2": ["block", "mono"],
    "Octal": ["mini", "mono", "digital"],
    "Ogre": ["classic", "serif"],
    "Old Banner": ["classic", "block"],
    # P
    "Pagga": ["block", "digital"],
    "Patorjk's Cheese": ["decorative", "3d", "serif"],
    "Patorjk-HeX": ["decorative", "3d"],
    "Pawp": ["classic", "sans"],
    "Peaks": ["decorative", "classic"],
    "Peaks Slant": ["slant", "lean"],
    "Pebbles": ["classic", "serif"],
    "Pepper": ["mini", "lean"],
    "Poison": ["decorative", "gothic"],
    "Puffy": ["bubble", "decorative"],
    "Puzzle": ["decorative", "weird"],
    "Pyramid": ["decorative", "mini", "weird"],
    # R
    "Rammstein": ["block", "classic"],
    "Rebel": ["block", "graffiti"],
    "Rectangles": ["mini", "block"],
    "Red Phoenix": ["serif", "classic"],
    "Relief": ["block", "shadow"],
    "Relief2": ["block", "shadow"],
    "Reverse": ["block", "weird"],
    "Roman": ["serif", "classic"],
    "Rot13": ["mini", "mono", "weird"],
    "Rotated": ["weird", "mini"],
    "Rounded": ["classic", "sans"],
    "Rowan Cap": ["sans", "lean"],
    "Rozzo": ["classic", "sans"],
    "RubiFont": ["block", "classic"],
    "Runic": ["weird", "gothic"],
    "Runyc": ["weird", "gothic"],
    # S
    "S Blood": ["decorative", "gothic"],
    "SL Script": ["cursive", "lean", "mini"],
    "Santa Clara": ["cursive", "lean", "mini"],
    "Script": ["cursive", "classic"],
    "Serifcap": ["serif", "classic", "mini"],
    "Shaded Blocky": ["block", "shadow", "3d"],
    "Shadow": ["shadow", "classic"],
    "Shimrod": ["lean", "mini"],
    "Short": ["mini", "lean"],
    "Slant": ["slant", "classic"],
    "Slant Relief": ["slant", "3d", "decorative"],
    "Slide": ["block", "weird"],
    "Small": ["classic", "mini", "serif"],
    "Small ASCII 12": ["mono", "classic"],
    "Small ASCII 9": ["mono", "mini"],
    "Small Block": ["block", "mini"],
    "Small Braille": ["digital", "mini", "weird"],
    "Small Caps": ["serif", "classic"],
    "Small Isometric1": ["3d", "decorative"],
    "Small Keyboard": ["block", "digital", "decorative"],
    "Small Mono 12": ["mono", "block"],
    "Small Mono 9": ["mono", "mini"],
    "Small Poison": ["decorative", "gothic"],
    "Small Script": ["cursive", "lean", "mini"],
    "Small Shadow": ["shadow", "mini"],
    "Small Slant": ["slant", "mini"],
    "Small Tengwar": ["weird", "mini"],
    "Soft": ["classic", "sans"],
    "Speed": ["slant", "tech"],
    "Spliff": ["classic", "block"],
    "Stacey": ["block", "classic"],
    "Stampate": ["lean", "cursive"],
    "Stampatello": ["lean", "cursive"],
    "Standard": ["classic", "serif"],
    "Star Strips": ["block", "decorative"],
    "Star Wars": ["classic", "block"],
    "Stellar": ["decorative", "classic"],
    "Stforek": ["mini", "classic"],
    "Stick Letters": ["lean", "classic", "mini"],
    "Stop": ["classic", "sans"],
    "Straight": ["mini", "lean"],
    "Stronger Than All": ["decorative", "serif"],
    "Sub-Zero": ["tech", "lean", "sans"],
    "Swamp Land": ["decorative", "gothic"],
    "Swan": ["lean", "classic"],
    "Sweet": ["decorative", "bubble", "serif"],
    # T
    "THIS": ["block", "decorative"],
    "Tanja": ["lean", "sans"],
    "Tengwar": ["decorative", "cursive"],
    "Term": ["mini", "mono"],
    "Terrace": ["block", "sans"],
    "Test1": ["decorative", "block"],
    "The Edge": ["block", "decorative"],
    "Thick": ["classic", "sans"],
    "Thin": ["lean", "classic"],
    "Thorned": ["lean", "weird"],
    "Three Point": ["mini", "lean"],
    "Ticks": ["decorative", "weird"],
    "Ticks Slant": ["decorative", "slant", "weird"],
    "Tiles": ["lean", "digital"],
    "Tinker-Toy": ["lean", "sans", "mini"],
    "Tmplr": ["mini", "block"],
    "Tombstone": ["lean", "classic"],
    "Train": ["decorative", "classic"],
    "Trek": ["tech", "sans"],
    "Tsalagi": ["classic", "serif"],
    "Tubular": ["lean", "sans"],
    "Twisted": ["decorative", "3d"],
    "Two Point": ["mini", "lean"],
    # U
    "USA Flag": ["block", "classic"],
    "Univers": ["classic", "serif"],
    "Upside Down Text": ["mini", "weird"],
    # V
    "Varsity": ["serif", "classic"],
    # W
    "Wavescape": ["lean", "classic"],
    "Wavy": ["mini", "weird", "cursive"],
    "Weird": ["lean", "weird"],
    "Wet Letter": ["classic", "decorative"],
    "Whimsy": ["decorative", "cursive"],
    "WideTerm": ["mini", "mono"],
    "Wow": ["mini", "block", "tech"],
}


SIZES = {
    "xs": "Extra small (1-3 lines)",
    "sm": "Small (4-5 lines)",
    "md": "Medium (6-8 lines)",
    "lg": "Large (9-12 lines)",
    "xl": "Extra large (13+ lines)",
}

SIZE_ORDER = {"xs": 0, "sm": 1, "md": 2, "lg": 3, "xl": 4}

# Maps font name -> {"size": str, "legibility": int (1-5)}
FONT_METRICS: dict[str, dict] = {
    "1Row": {"size": "xs", "legibility": 3},
    "3-D": {"size": "md", "legibility": 5},
    "3D Diagonal": {"size": "xl", "legibility": 4},
    "3D-ASCII": {"size": "lg", "legibility": 4},
    "3x5": {"size": "md", "legibility": 5},
    "4Max": {"size": "sm", "legibility": 4},
    "5 Line Oblique": {"size": "md", "legibility": 5},
    "Acrobatic": {"size": "lg", "legibility": 4},
    "Alligator": {"size": "md", "legibility": 5},
    "Alligator2": {"size": "md", "legibility": 5},
    "Alpha": {"size": "xl", "legibility": 4},
    "Alphabet": {"size": "md", "legibility": 5},
    "AMC 3 Line": {"size": "sm", "legibility": 4},
    "AMC 3 Liv1": {"size": "sm", "legibility": 4},
    "AMC AAA01": {"size": "xl", "legibility": 4},
    "AMC Neko": {"size": "lg", "legibility": 4},
    "AMC Razor": {"size": "md", "legibility": 4},
    "AMC Razor2": {"size": "lg", "legibility": 5},
    "AMC Slash": {"size": "lg", "legibility": 4},
    "AMC Slider": {"size": "md", "legibility": 4},
    "AMC Thin": {"size": "md", "legibility": 5},
    "AMC Tubes": {"size": "md", "legibility": 4},
    "AMC Untitled": {"size": "md", "legibility": 5},
    "ANSI Compact": {"size": "md", "legibility": 3},
    "ANSI Regular": {"size": "md", "legibility": 4},
    "ANSI Shadow": {"size": "md", "legibility": 2},
    "Arrows": {"size": "md", "legibility": 5},
    "ASCII 12": {"size": "lg", "legibility": 5},
    "ASCII 9": {"size": "md", "legibility": 5},
    "ASCII New Roman": {"size": "sm", "legibility": 4},
    "Avatar": {"size": "md", "legibility": 4},
    "B1FF": {"size": "xs", "legibility": 3},
    "Babyface Lame": {"size": "sm", "legibility": 5},
    "Babyface Leet": {"size": "sm", "legibility": 4},
    "Banner": {"size": "md", "legibility": 4},
    "Banner3": {"size": "md", "legibility": 5},
    "Banner3-D": {"size": "md", "legibility": 4},
    "Banner4": {"size": "md", "legibility": 4},
    "Barbwire": {"size": "md", "legibility": 5},
    "Basic": {"size": "md", "legibility": 5},
    "Bear": {"size": "lg", "legibility": 4},
    "Bell": {"size": "md", "legibility": 4},
    "Benjamin": {"size": "xs", "legibility": 3},
    "Big": {"size": "md", "legibility": 5},
    "Big ASCII 12": {"size": "xl", "legibility": 4},
    "Big ASCII 9": {"size": "xl", "legibility": 4},
    "Big Chief": {"size": "md", "legibility": 4},
    "Big Money-ne": {"size": "lg", "legibility": 4},
    "Big Money-nw": {"size": "lg", "legibility": 4},
    "Big Money-se": {"size": "lg", "legibility": 4},
    "Big Money-sw": {"size": "lg", "legibility": 4},
    "Big Mono 12": {"size": "xl", "legibility": 3},
    "Big Mono 9": {"size": "xl", "legibility": 3},
    "Bigfig": {"size": "xs", "legibility": 4},
    "Binary": {"size": "xs", "legibility": 3},
    "Block": {"size": "md", "legibility": 5},
    "Blocks": {"size": "lg", "legibility": 3},
    "Bloody": {"size": "lg", "legibility": 3},
    "BlurVision ASCII": {"size": "lg", "legibility": 2},
    "Bolger": {"size": "md", "legibility": 4},
    "Braced": {"size": "sm", "legibility": 4},
    "Bright": {"size": "md", "legibility": 4},
    "Broadway": {"size": "lg", "legibility": 4},
    "Broadway KB": {"size": "xs", "legibility": 4},
    "Bubble": {"size": "sm", "legibility": 4},
    "Bulbhead": {"size": "sm", "legibility": 4},
    "Caligraphy": {"size": "xl", "legibility": 4},
    "Caligraphy2": {"size": "xl", "legibility": 4},
    "Calvin S": {"size": "xs", "legibility": 2},
    "Cards": {"size": "md", "legibility": 3},
    "Catwalk": {"size": "md", "legibility": 5},
    "Chiseled": {"size": "lg", "legibility": 4},
    "Chunky": {"size": "sm", "legibility": 4},
    "Circle": {"size": "xs", "legibility": 2},
    "Classy": {"size": "lg", "legibility": 4},
    "Coder Mini": {"size": "md", "legibility": 4},
    "Coinstak": {"size": "md", "legibility": 5},
    "Cola": {"size": "md", "legibility": 5},
    "Colossal": {"size": "lg", "legibility": 4},
    "Computer": {"size": "md", "legibility": 5},
    "Contessa": {"size": "sm", "legibility": 4},
    "Contrast": {"size": "md", "legibility": 4},
    "Cosmike": {"size": "md", "legibility": 3},
    "Cosmike2": {"size": "lg", "legibility": 4},
    "Crawford": {"size": "md", "legibility": 4},
    "Crawford2": {"size": "md", "legibility": 5},
    "Crazy": {"size": "xl", "legibility": 4},
    "Cricket": {"size": "md", "legibility": 5},
    "Cursive": {"size": "md", "legibility": 5},
    "Cyberlarge": {"size": "sm", "legibility": 4},
    "Cybermedium": {"size": "sm", "legibility": 5},
    "Cybersmall": {"size": "xs", "legibility": 3},
    "Cygnet": {"size": "sm", "legibility": 4},
    "DANC4": {"size": "sm", "legibility": 4},
    "Dancing Font": {"size": "md", "legibility": 4},
    "Decimal": {"size": "xs", "legibility": 3},
    "Def Leppard": {"size": "xl", "legibility": 3},
    "Delta Corps Priest 1": {"size": "lg", "legibility": 4},
    "DiamFont": {"size": "md", "legibility": 3},
    "Diamond": {"size": "md", "legibility": 5},
    "Diet Cola": {"size": "md", "legibility": 5},
    "Digital": {"size": "xs", "legibility": 3},
    "Doh": {"size": "xl", "legibility": 4},
    "Doom": {"size": "md", "legibility": 5},
    "DOS Rebel": {"size": "lg", "legibility": 3},
    "Dot Matrix": {"size": "lg", "legibility": 5},
    "Double": {"size": "sm", "legibility": 5},
    "Double Shorts": {"size": "xs", "legibility": 3},
    "Dr Pepper": {"size": "sm", "legibility": 5},
    "DWhistled": {"size": "lg", "legibility": 4},
    "Efti Chess": {"size": "sm", "legibility": 3},
    "Efti Font": {"size": "sm", "legibility": 4},
    "Efti Italic": {"size": "sm", "legibility": 4},
    "Efti Piti": {"size": "xs", "legibility": 4},
    "Efti Robot": {"size": "md", "legibility": 5},
    "Efti Wall": {"size": "sm", "legibility": 3},
    "Efti Water": {"size": "sm", "legibility": 4},
    "Electronic": {"size": "lg", "legibility": 3},
    "Elite": {"size": "sm", "legibility": 2},
    "Emboss": {"size": "xs", "legibility": 2},
    "Emboss 2": {"size": "xs", "legibility": 2},
    "Epic": {"size": "lg", "legibility": 5},
    "Fender": {"size": "md", "legibility": 5},
    "Filter": {"size": "sm", "legibility": 4},
    "Fire Font-k": {"size": "lg", "legibility": 4},
    "Fire Font-s": {"size": "lg", "legibility": 4},
    "Flipped": {"size": "sm", "legibility": 4},
    "Flower Power": {"size": "lg", "legibility": 4},
    "Font Font": {"size": "lg", "legibility": 4},
    "Four Tops": {"size": "sm", "legibility": 4},
    "Fraktur": {"size": "xl", "legibility": 3},
    "Fun Face": {"size": "md", "legibility": 4},
    "Fun Faces": {"size": "md", "legibility": 4},
    "Future": {"size": "xs", "legibility": 2},
    "Future Smooth": {"size": "xs", "legibility": 2},
    "Future Thin": {"size": "xs", "legibility": 2},
    "Fuzzy": {"size": "md", "legibility": 5},
    "Georgi16": {"size": "xl", "legibility": 4},
    "Georgia11": {"size": "lg", "legibility": 3},
    "Ghost": {"size": "lg", "legibility": 4},
    "Ghoulish": {"size": "md", "legibility": 5},
    "Glenyn": {"size": "sm", "legibility": 4},
    "Goofy": {"size": "md", "legibility": 5},
    "Gothic": {"size": "lg", "legibility": 4},
    "Graceful": {"size": "sm", "legibility": 4},
    "Gradient": {"size": "lg", "legibility": 3},
    "Graffiti": {"size": "md", "legibility": 5},
    "Greek": {"size": "lg", "legibility": 4},
    "Heart Left": {"size": "sm", "legibility": 4},
    "Heart Right": {"size": "sm", "legibility": 4},
    "Henry 3D": {"size": "md", "legibility": 4},
    "Hex": {"size": "xs", "legibility": 3},
    "Hieroglyphs": {"size": "sm", "legibility": 4},
    "Hollywood": {"size": "lg", "legibility": 4},
    "Horizontal Left": {"size": "md", "legibility": 4},
    "Horizontal Right": {"size": "md", "legibility": 4},
    "ICL-1900": {"size": "xl", "legibility": 4},
    "Impossible": {"size": "lg", "legibility": 4},
    "Invita": {"size": "md", "legibility": 5},
    "Isometric1": {"size": "lg", "legibility": 4},
    "Isometric2": {"size": "lg", "legibility": 4},
    "Isometric3": {"size": "lg", "legibility": 4},
    "Isometric4": {"size": "lg", "legibility": 4},
    "Italic": {"size": "sm", "legibility": 4},
    "Ivrit": {"size": "md", "legibility": 5},
    "Jacky": {"size": "md", "legibility": 5},
    "Jazmine": {"size": "lg", "legibility": 4},
    "Jerusalem": {"size": "md", "legibility": 5},
    "JS Block Letters": {"size": "xs", "legibility": 3},
    "JS Bracket Letters": {"size": "sm", "legibility": 4},
    "JS Capital Curves": {"size": "sm", "legibility": 4},
    "JS Cursive": {"size": "md", "legibility": 5},
    "JS Stick Letters": {"size": "sm", "legibility": 5},
    "Katakana": {"size": "md", "legibility": 4},
    "Kban": {"size": "md", "legibility": 5},
    "Keyboard": {"size": "lg", "legibility": 4},
    "Knob": {"size": "sm", "legibility": 4},
    "Konto": {"size": "xs", "legibility": 2},
    "Konto Slant": {"size": "xs", "legibility": 3},
    "Larry 3D": {"size": "lg", "legibility": 4},
    "Larry 3D 2": {"size": "lg", "legibility": 4},
    "LCD": {"size": "md", "legibility": 4},
    "Lean": {"size": "md", "legibility": 4},
    "Letter": {"size": "md", "legibility": 5},
    "Letters": {"size": "md", "legibility": 5},
    "Lil Devil": {"size": "md", "legibility": 4},
    "Line Blocks": {"size": "sm", "legibility": 5},
    "Linux": {"size": "sm", "legibility": 3},
    "Lockergnome": {"size": "sm", "legibility": 4},
    "Madrid": {"size": "sm", "legibility": 5},
    "Marquee": {"size": "md", "legibility": 5},
    "Maxfour": {"size": "sm", "legibility": 4},
    "Merlin1": {"size": "md", "legibility": 4},
    "Merlin2": {"size": "lg", "legibility": 4},
    "Mike": {"size": "xs", "legibility": 4},
    "Mini": {"size": "sm", "legibility": 3},
    "miniwi": {"size": "sm", "legibility": 2},
    "Mirror": {"size": "md", "legibility": 5},
    "Mnemonic": {"size": "xs", "legibility": 3},
    "Modular": {"size": "md", "legibility": 5},
    "Mono 12": {"size": "lg", "legibility": 4},
    "Mono 9": {"size": "md", "legibility": 4},
    "Morse": {"size": "xs", "legibility": 3},
    "Morse2": {"size": "xs", "legibility": 3},
    "Moscow": {"size": "md", "legibility": 5},
    "Mshebrew210": {"size": "sm", "legibility": 5},
    "Muzzle": {"size": "sm", "legibility": 5},
    "Nancyj": {"size": "md", "legibility": 5},
    "Nancyj-Fancy": {"size": "md", "legibility": 5},
    "Nancyj-Improved": {"size": "md", "legibility": 5},
    "Nancyj-Underlined": {"size": "md", "legibility": 5},
    "Nipples": {"size": "md", "legibility": 5},
    "NScript": {"size": "xl", "legibility": 4},
    "NT Greek": {"size": "lg", "legibility": 4},
    "NV Script": {"size": "xl", "legibility": 4},
    "O8": {"size": "md", "legibility": 4},
    "Octal": {"size": "xs", "legibility": 2},
    "Ogre": {"size": "md", "legibility": 5},
    "Old Banner": {"size": "md", "legibility": 5},
    "OS2": {"size": "md", "legibility": 4},
    "Pagga": {"size": "xs", "legibility": 2},
    "Patorjk's Cheese": {"size": "xl", "legibility": 4},
    "Patorjk-HeX": {"size": "lg", "legibility": 4},
    "Pawp": {"size": "lg", "legibility": 4},
    "Peaks": {"size": "md", "legibility": 5},
    "Peaks Slant": {"size": "md", "legibility": 4},
    "Pebbles": {"size": "lg", "legibility": 4},
    "Pepper": {"size": "sm", "legibility": 4},
    "Poison": {"size": "lg", "legibility": 4},
    "Puffy": {"size": "md", "legibility": 5},
    "Puzzle": {"size": "sm", "legibility": 4},
    "Pyramid": {"size": "xs", "legibility": 3},
    "Rammstein": {"size": "md", "legibility": 5},
    "Rebel": {"size": "lg", "legibility": 3},
    "Rectangles": {"size": "md", "legibility": 4},
    "Red Phoenix": {"size": "md", "legibility": 5},
    "Relief": {"size": "md", "legibility": 4},
    "Relief2": {"size": "md", "legibility": 4},
    "Reverse": {"size": "lg", "legibility": 4},
    "Roman": {"size": "lg", "legibility": 4},
    "Rot13": {"size": "xs", "legibility": 3},
    "Rotated": {"size": "xs", "legibility": 4},
    "Rounded": {"size": "md", "legibility": 5},
    "Rowan Cap": {"size": "md", "legibility": 4},
    "Rozzo": {"size": "md", "legibility": 5},
    "RubiFont": {"size": "md", "legibility": 3},
    "Runic": {"size": "md", "legibility": 5},
    "Runyc": {"size": "md", "legibility": 5},
    "S Blood": {"size": "md", "legibility": 5},
    "Santa Clara": {"size": "md", "legibility": 5},
    "Script": {"size": "md", "legibility": 5},
    "Serifcap": {"size": "sm", "legibility": 4},
    "Shaded Blocky": {"size": "md", "legibility": 4},
    "Shadow": {"size": "sm", "legibility": 5},
    "Shimrod": {"size": "md", "legibility": 5},
    "Short": {"size": "xs", "legibility": 4},
    "SL Script": {"size": "md", "legibility": 5},
    "Slant": {"size": "md", "legibility": 5},
    "Slant Relief": {"size": "lg", "legibility": 4},
    "Slide": {"size": "md", "legibility": 4},
    "Small": {"size": "sm", "legibility": 4},
    "Small ASCII 12": {"size": "lg", "legibility": 4},
    "Small ASCII 9": {"size": "md", "legibility": 4},
    "Small Block": {"size": "sm", "legibility": 3},
    "Small Braille": {"size": "xs", "legibility": 2},
    "Small Caps": {"size": "sm", "legibility": 5},
    "Small Isometric1": {"size": "md", "legibility": 5},
    "Small Keyboard": {"size": "sm", "legibility": 3},
    "Small Mono 12": {"size": "lg", "legibility": 3},
    "Small Mono 9": {"size": "md", "legibility": 3},
    "Small Poison": {"size": "md", "legibility": 5},
    "Small Script": {"size": "sm", "legibility": 5},
    "Small Shadow": {"size": "sm", "legibility": 4},
    "Small Slant": {"size": "sm", "legibility": 4},
    "Small Tengwar": {"size": "xs", "legibility": 4},
    "Soft": {"size": "md", "legibility": 4},
    "Speed": {"size": "md", "legibility": 4},
    "Spliff": {"size": "sm", "legibility": 4},
    "Stacey": {"size": "md", "legibility": 5},
    "Stampate": {"size": "md", "legibility": 4},
    "Stampatello": {"size": "md", "legibility": 4},
    "Standard": {"size": "md", "legibility": 5},
    "Star Strips": {"size": "lg", "legibility": 4},
    "Star Wars": {"size": "md", "legibility": 5},
    "Stellar": {"size": "md", "legibility": 5},
    "Stforek": {"size": "sm", "legibility": 4},
    "Stick Letters": {"size": "sm", "legibility": 5},
    "Stop": {"size": "md", "legibility": 5},
    "Straight": {"size": "sm", "legibility": 3},
    "Stronger Than All": {"size": "lg", "legibility": 3},
    "Sub-Zero": {"size": "md", "legibility": 4},
    "Swamp Land": {"size": "md", "legibility": 4},
    "Swan": {"size": "lg", "legibility": 4},
    "Sweet": {"size": "xl", "legibility": 4},
    "Tanja": {"size": "md", "legibility": 4},
    "Tengwar": {"size": "lg", "legibility": 4},
    "Term": {"size": "xs", "legibility": 3},
    "Terrace": {"size": "lg", "legibility": 4},
    "Test1": {"size": "sm", "legibility": 3},
    "The Edge": {"size": "md", "legibility": 4},
    "Thick": {"size": "sm", "legibility": 4},
    "Thin": {"size": "md", "legibility": 5},
    "THIS": {"size": "md", "legibility": 4},
    "Thorned": {"size": "sm", "legibility": 5},
    "Three Point": {"size": "xs", "legibility": 3},
    "Ticks": {"size": "md", "legibility": 4},
    "Ticks Slant": {"size": "md", "legibility": 4},
    "Tiles": {"size": "md", "legibility": 5},
    "Tinker-Toy": {"size": "md", "legibility": 5},
    "Tmplr": {"size": "sm", "legibility": 3},
    "Tombstone": {"size": "sm", "legibility": 5},
    "Train": {"size": "md", "legibility": 4},
    "Trek": {"size": "md", "legibility": 4},
    "Tsalagi": {"size": "sm", "legibility": 4},
    "Tubular": {"size": "md", "legibility": 5},
    "Twisted": {"size": "md", "legibility": 4},
    "Two Point": {"size": "xs", "legibility": 3},
    "Univers": {"size": "lg", "legibility": 4},
    "Upside Down Text": {"size": "xs", "legibility": 2},
    "USA Flag": {"size": "md", "legibility": 5},
    "Varsity": {"size": "md", "legibility": 5},
    "Wavescape": {"size": "xl", "legibility": 4},
    "Wavy": {"size": "sm", "legibility": 4},
    "Weird": {"size": "md", "legibility": 5},
    "Wet Letter": {"size": "md", "legibility": 5},
    "Whimsy": {"size": "lg", "legibility": 4},
    "WideTerm": {"size": "xs", "legibility": 2},
    "Wow": {"size": "xs", "legibility": 2},
}


def get_tags(font_name: str) -> list[str]:
    """Get category tags for a font. Falls back to case-insensitive match."""
    if font_name in FONT_TAGS:
        return FONT_TAGS[font_name]
    lower = font_name.lower()
    for name, tags in FONT_TAGS.items():
        if name.lower() == lower:
            return tags
    return []


def get_metrics(font_name: str) -> dict:
    """Get size and legibility metrics for a font."""
    if font_name in FONT_METRICS:
        return FONT_METRICS[font_name]
    lower = font_name.lower()
    for name, m in FONT_METRICS.items():
        if name.lower() == lower:
            return m
    return {"size": "md", "legibility": 3}


def fonts_by_tag(tag: str) -> list[str]:
    """Return all font names that have the given tag."""
    tag = tag.lower()
    return sorted(
        [name for name, tags in FONT_TAGS.items() if tag in tags],
        key=str.lower,
    )


def fonts_by_size(size: str) -> list[str]:
    """Return all font names matching the given size (xs/sm/md/lg/xl)."""
    size = size.lower()
    return sorted(
        [name for name, m in FONT_METRICS.items() if m["size"] == size],
        key=str.lower,
    )


def sort_fonts(
    names: list[str],
    sort_by: str = "name",
) -> list[str]:
    """Sort font names by: name, size, legibility."""
    if sort_by == "size":
        return sorted(names, key=lambda n: (SIZE_ORDER.get(get_metrics(n)["size"], 2), n.lower()))
    elif sort_by == "legibility":
        return sorted(names, key=lambda n: (-get_metrics(n)["legibility"], n.lower()))
    return sorted(names, key=str.lower)
